### ISSUE TITLE
[Odoo Products] Add AND expression when searching name, categoryId

### ISSUE THREAD

**Issue by hgbdev** [telecelplay/mv-odoo#1] opened 2022-01-10 04:20 UTC
**Problem**
- Incorrect product returned when searching name and productId

**Todo**
- [x] Modify odooProducts meveo module
- [ ] Done

Video: https://vimeo.com/664093034

**Comment by smichea** [comment] 2022-01-18 00:01
duplicate of https://github.com/telecelplay/odoo-telecelplay-marketplace/issues/6

**Closed by smichea** 2022-01-18 00:01 UTC
